import Image from "next/image";
import Link from "next/link";
import MarketingFooter from "@/components/marketing/MarketingFooter";
import MarketingNav from "@/components/marketing/MarketingNav";
import PricingSection from "@/components/marketing/PricingSection";

const features=[
  ["01","Record without the setup","Capture studio-quality conversations in your browser or upload the audio you already have."],
  ["02","Let AI handle the busywork","Turn recordings into transcripts, show notes, chapters, artwork, and social posts in a few clicks."],
  ["03","Publish with confidence","Create a polished public page and a validated RSS feed ready for the platforms your audience uses."],
  ["04","Grow as one team","Invite producers and editors, assign the right access, and keep every show moving in one workspace."],
];
const steps=[["Create your show","Start fresh or bring in an existing RSS feed."],["Record and refine","Capture audio, edit the transcript, and generate your production package."],["Publish and grow","Share your episode, review performance, and plan what comes next."]];
const faqs=[["Can I start for free?","Yes. Build your first show and learn the workflow before upgrading for more publishing capacity and AI tools."],["Can I import an existing podcast?","Yes. Paste your RSS feed to preview and import your show and episodes."],["Do I need special recording equipment?","No. Record from a supported browser or upload audio from any setup."],["Where can I distribute my show?","Your standards-based RSS feed can be submitted to Spotify, Apple Podcasts, and other directories."],["Can my team work with me?","Yes. Studio workspaces support show-level roles for owners, producers, editors, and viewers."]];

export default function Home(){return <main className="marketing-shell"><MarketingNav/>
  <section className="relative overflow-hidden px-5 pb-20 pt-10 sm:px-8 lg:pb-28 lg:pt-16"><div className="marketing-orb marketing-orb-one"/><div className="marketing-orb marketing-orb-two"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.02fr_.98fr]">
    <div className="relative z-10"><div className="marketing-kicker"><span/>The creator studio, reimagined</div><h1 className="mt-7 max-w-3xl text-[clamp(4rem,9vw,7.8rem)] font-semibold leading-[.82] tracking-[-.075em] text-white">Create.<br/>Publish.<br/><em>Be Heard.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/68 sm:text-xl">Record, shape, and share remarkable podcasts from one intelligent studio built for modern creators.</p><div className="mt-10 flex flex-col gap-4 sm:flex-row"><Link href="/dashboard" className="marketing-button marketing-button-primary">Enter the studio <span>→</span></Link><Link href="#how-it-works" className="marketing-button marketing-button-secondary">See how it works</Link></div><p className="mt-5 text-sm text-white/42">Development access · Sign-in will return before launch</p></div>
    <div className="relative mx-auto w-full max-w-[620px]"><div className="hero-halo"/><div className="hero-frame"><Image src="/hero-image.jpg" alt="Podcast creator speaking into a studio microphone" width={1100} height={1250} priority className="h-full w-full object-cover"/><div className="hero-image-wash"/><div className="absolute left-5 top-5 flex items-center gap-2 rounded-full border border-white/15 bg-black/35 px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-white backdrop-blur-xl"><span className="h-2 w-2 animate-pulse rounded-full bg-[#ff4f8b]"/>Live studio</div><div className="hero-player"><button aria-label="Play preview" className="hero-play">▶</button><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">Your next great episode</p><div className="mt-3 h-2 rounded-full bg-white/15"><div className="h-full w-2/3 rounded-full bg-[#ff83b1]"/></div></div><span className="text-xs text-white/50">24:18</span></div></div><div className="hero-note hero-note-top">AI show notes<br/><strong>Ready in seconds</strong></div><div className="hero-note hero-note-bottom"><span>↗</span><div><strong>Episode published</strong><br/>Your audience is listening</div></div></div>
  </div></section>
  <section id="features" className="marketing-section bg-[#f4f0e8] text-[#171717]"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="section-eyebrow text-[#7158e8]">Everything in one studio</p><h2 className="section-title mt-5">Less production.<br/><em>More creating.</em></h2></div><p className="max-w-xl text-lg leading-8 text-black/58 lg:justify-self-end">SoundStage clears away repetitive work between your idea and your audience—without taking creative decisions out of your hands.</p></div><div className="mt-16 grid border-l border-t border-black/12 sm:grid-cols-2">{features.map(([number,title,copy])=><article key={number} className="feature-cell border-b border-r border-black/12 p-8 sm:p-10"><span className="text-xs font-bold tracking-[.2em] text-[#7158e8]">{number}</span><h3 className="mt-16 text-2xl font-semibold tracking-tight">{title}</h3><p className="mt-4 max-w-md leading-7 text-black/55">{copy}</p></article>)}</div></div></section>
  <section id="how-it-works" className="marketing-section bg-[#151515] text-white"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-[#ff7cad]">A simpler way to ship</p><div className="mt-5 grid gap-10 lg:grid-cols-2"><h2 className="section-title">From first take<br/>to <em>every platform.</em></h2><div>{steps.map(([title,copy],i)=><article key={title} className="step-card"><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></div></section>
  <PricingSection/>
  <section id="faq" className="marketing-section bg-[#ece6da] text-[#171717]"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="section-eyebrow text-[#7158e8]">Questions, answered</p><h2 className="section-title mt-5">Good to<br/><em>know.</em></h2></div><div className="border-t border-black/15">{faqs.map(([q,a])=><details key={q} className="faq-item"><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
  <section className="bg-[#7158e8] px-5 py-20 text-center text-white sm:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-white/65">Your voice belongs out there</p><h2 className="mx-auto mt-6 max-w-5xl text-[clamp(3.5rem,8vw,7rem)] font-semibold leading-[.9] tracking-[-.065em]">Ready to make<br/><em>something worth hearing?</em></h2><Link href="/dashboard" className="marketing-button mt-10 inline-flex bg-white text-[#171717]">Enter the studio <span>→</span></Link></div></section><MarketingFooter/>
</main>}
